# Generated by Django 4.2.7 on 2023-11-29 21:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_material_product_material"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("name",),
                "verbose_name": "Category",
                "verbose_name_plural": "Category",
            },
        ),
        migrations.AlterModelOptions(
            name="images",
            options={
                "ordering": ("-product",),
                "verbose_name": "Images",
                "verbose_name_plural": "Images",
            },
        ),
    ]
