# Generated by Django 4.2.7 on 2023-12-04 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_product_height_product_width"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="uploads/,"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productimg",
                        to="product.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Images",
                "verbose_name_plural": "Images",
                "ordering": ("-product",),
            },
        ),
        migrations.DeleteModel(
            name="images",
        ),
    ]
