# Generated by Django 4.2.7 on 2023-12-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_productimg_delete_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimg",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
