# Generated by Django 4.2.7 on 2023-12-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_alter_productimg_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimg",
            name="thumbnail",
            field=models.ImageField(blank=True, upload_to="uploads/"),
        ),
    ]
