# Generated by Django 4.2.7 on 2023-12-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0009_productimg_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="height",
        ),
        migrations.RemoveField(
            model_name="product",
            name="width",
        ),
        migrations.AddField(
            model_name="product",
            name="Sizes",
            field=models.TextField(blank=True, default="100cmX100cm", null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="location",
            field=models.CharField(default="Storage", max_length=255),
        ),
    ]
