# Generated by Django 4.2.7 on 2023-12-06 17:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0012_alter_product_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("name",),
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
    ]
