# Generated by Django 4.2.7 on 2023-12-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0014_rename_category_productcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
