# Generated by Django 4.2.7 on 2023-12-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0015_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
