# Generated by Django 4.2.7 on 2023-12-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0016_alter_product_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.AddField(
            model_name="productsizes",
            name="price",
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=9),
            preserve_default=False,
        ),
    ]
