# Generated by Django 4.2.7 on 2023-12-10 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("product", "0016_alter_product_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="order_detail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=199)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=256)),
                ("address", models.TextField(blank=True, null=True)),
                ("ExtraNotes", models.TextField(blank=True, null=True)),
                ("zipcode", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("prePaid", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "Cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=50, null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="order_item",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("price", models.DecimalField(decimal_places=2, max_digits=9)),
                ("size", models.CharField(max_length=100)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "Product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="product.product",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="order.order_detail",
                    ),
                ),
            ],
            options={
                "ordering": ["-order__created_at"],
            },
        ),
    ]
