# Generated by Django 4.2.7 on 2023-12-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order_item",
            old_name="Product",
            new_name="product",
        ),
        migrations.RemoveField(
            model_name="order_detail",
            name="Cost",
        ),
        migrations.AddField(
            model_name="order_detail",
            name="newOrder",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="order_detail",
            name="ordertotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
